# config.yaml

sample_ids:
  - TENX99  # 25080 patches -> 20761 patches 
  - TENX95  # 11845 patches -> 7760 patches 
  - NCBI785 # 4180 patches -> 4010 patches
  - NCBI783 # 3869 patches -> 3005 patches

h5_dir: /root/workspace/h5radiomics/h5
output_root: /root/workspace/h5radiomics/outputs
label: 255
save_patches: false # true

classes:
  - firstorder
  - glcm
  - glrlm
  - glszm
  - gldm
  - ngtdm

filters:
  - Original
  - Wavelet
  - LoG
  - Square
  - SquareRoot
  - Logarithm
  - Exponential

processing:
  lower_q: 0.01
  upper_q: 0.99
  save_processed: true