sample_ids:
  - TENX99
  - TENX95
  - NCBI785
  - NCBI783

input_dir: /root/workspace/hest-radiomics/data/h5
output_dir: /root/workspace/hest-radiomics/data/outputs

label: 255
save_patches: true
num_workers: 8

classes:
  - firstorder
  - glcm
  - glrlm
  - glszm
  - gldm
  - ngtdm

filters:
  - Original
  # - Wavelet
  # - LoG
  # - Square
  # - SquareRoot
  # - Logarithm
  # - Exponential

image_type_settings:
  LoG:
    sigma: [1.0, 2.0, 3.0]

# cellseg-based extraction
mask_source: cellseg          # threshold | cellseg
celltype_mode: merged      # merged | per_class | single  
target_cell_type: null        # used only when celltype_mode=single

# if null, run_extract.py should resolve:
# {output_dir}/{sample_id}/cellvitseg/cellseg.parquet
cellseg_path: null

processing:
  lower_q: 0.01
  upper_q: 0.99
  save_processed: true